---
jobName: "metadata"
jobDesc: "metadata transfer"
source:
  source_type: "FILE_SYSTEM"
  path: "/src/etc/some/path"
  file_Type: "csv"
  job_Configurations:
  - columns:
    - name: "id"
      type: "number"
      value_range: null
    - name: "salary"
      type: "float"
      value_range: null
    - name: "name"
      type: "string"
      value_range: null
    - name: "image"
      type: "binary"
      value_range: null
